src/filters/fs.rs
src/filters/path.rs
src/route.rs
tests/path.rs

Closes #13 
Something like this, @lnicola?

add warp::path::tail() filter

---

examples/body.rs
examples/errors.rs
examples/file.rs
examples/handlebars_template.rs
examples/headers.rs
examples/routing.rs
examples/todos.rs
src/filters/fs.rs
src/filters/method.rs
src/filters/ws.rs
src/lib.rs
src/reply.rs
src/test.rs
tests/method.rs

refs #14
----
@kamalmarhubi I took what you started in #21 and applied the comments that I had left there, this is what it looks like. What do you think?

Add method::v2 filters that act like all the others

---

src/filter/mod.rs
src/filter/unify.rs
tests/filter.rs

add Filter::unify() to flatten Either<T, T>

---

src/filters/body.rs
src/filters/fs.rs
src/filters/path.rs
src/reject.rs
tests/fs.rs

Discussions: #37, #33 
It doesn't break anything, I've just added an error cause to a Rejection

Add cause to Rejection (WIP)

---

examples/handlebars_template.rs

Made most of handlebars example reusable in real application.

Better handlebars example

---

src/filters/path.rs
tests/path.rs

Add warp::path::full() filter

---

src/filters/reply.rs
tests/reply_with.rs

add warp::reply::with::headers(HeaderMap) filter

---

examples/errors.rs
src/reject.rs

Solve https://github.com/seanmonstar/warp/issues/37#issuecomment-422039319
* New method `Rejection::into_cause` which use to match an error cause.
* New method `Rejection::json()` which return a json response.
* Update a `errors.rs` example to show how to handle custom errors.

Improve error handling.

---

src/lib.rs
src/redirect.rs
tests/redirect.rs

add warp::redirect(as_location) reply helper

---

examples/dir.rs
examples/dir/another.html
examples/dir/index.html
src/filters/fs.rs
tests/fs.rs

 Add automatic insert for directory routes 

---

src/filters/path.rs
tests/path.rs

add warp::path::peek() to view the tail without altering matched path

---

examples/errors.rs
examples/file.rs
examples/handlebars_template.rs
examples/returning.rs
examples/todos.rs
examples/websockets_chat.rs
src/filters/path.rs
tests/path.rs

Rename `warp::path::index` to `warp::path::end`

---

src/filters/path.rs

Apply index => end name change to `filters::path` module docs.

Fix index reference in docs

---

src/filters/ws.rs
src/test.rs
tests/ws.rs

Add `warp::test::ws` test helpers

---

src/filters/cors.rs
tests/cors.rs

Adds access-control-allow-headers to cors

---

src/filters/cors.rs
tests/cors.rs

Add expose-headers to CORS

---

src/filters/query.rs

I also added a log message if the implementation defaults to an empty string if there is none provided.
While doing the code, I noticed that the behavior for the 2nd method is different. Is that on purpose?
Resolves #173.

Emit log messages when query string fails to deserialize

---

src/filters/cookie.rs
src/filters/fs.rs
src/filters/header.rs
tests/header.rs

Add warp::header::optional filter

---

src/filters/log.rs

Added more methods to warp::filters::log::Info

---

src/filters/fs.rs

See: https://docs.rs/mime_guess/2.0.1/mime_guess/fn.guess_mime_type.html

Fix depreciation warning from mime_guess create

---

src/filter/and.rs
src/filter/and_then.rs
src/filter/or.rs
src/filters/cors.rs
src/reject.rs

Refine Filter::or to propagate Never more eagerly

---

examples/todos.rs

`std::sync::Mutex` is not supposed to be used inside async functions, because it blocks the executor when it locks. Both tokio and async-std have their own versions of `Mutex` that don't block but instead have a `lock()` function that returns a future.
I hope that this honest mistake isn't a foreshadowing of a fear I've had for quite some time now, that because tons of common functions in the rust standard library and ecosystem are blocking, and because this blocking is often quite invisible, both in the code and in tests and even in production under low traffic load, that this kind of mistake is going to happen all the time in many projects and libraries. With as a result that everything works well until you actually get a higher traffic load and then performance falls off a cliff. …

Make todos example use tokio::sync::Mutex instead of std::sync::Mutex.

---

.github/workflows/ci.yml
README.md

Check Style is commented out because `master` needs some formatting.

Add GitHub workflow for CI

---

src/filters/ext.rs
src/route.rs
src/test.rs
tests/ext.rs

Remove warp::ext::set function

---

examples/tls.rs
src/error.rs
src/filters/body.rs
src/filters/multipart.rs
src/filters/ws.rs
src/server.rs
src/tls.rs

closes #223
@jxs I had some design changes to propose for #317, and figured I'd just put them into a commit.

Change Server::tls(path, path) to return a builder instead

---

src/filter/and.rs
src/filter/and_then.rs
src/filter/boxed.rs
src/filter/map.rs
src/filter/map_err.rs
src/filter/mod.rs
src/filter/or.rs
src/filter/or_else.rs
src/filter/recover.rs
src/filter/service.rs
src/filter/unify.rs
src/filter/untuple_one.rs
src/filters/any.rs
src/filters/body.rs
src/filters/cors.rs
src/filters/log.rs
src/filters/multipart.rs
src/test.rs

Add `Internal` argument to sealed Filter methods

---

.github/workflows/ci.yml
README.md
src/reject.rs
src/test.rs

- add step test for --no-default-features
- remove no longer used travis badge

- fix known_enum macro to allow attributes, fixes #352

---

.github/workflows/ci.yml
examples/unix_socket.rs

and adjust github workflow to test domain sockets too.
Fixes #365

Fix lifetime on unix_socket example

---

src/filters/path.rs
tests/path.rs

Change `warp::path` to work with any `AsRef<str>` argument.

---

src/filters/cors.rs

The `Builder` can still be used in exactly the same way, it is just
renamed, and has a new `build` method. Calling `build` allows
constructing a wrapping filter that does the same thing, but doesn't
need to pay any cost if re-using it.

Change `warp::cors()` to return a `Builder`

---

CHANGELOG.md
Cargo.toml
README.md
src/lib.rs

Prepare v0.2.0

---

src/filters/ws.rs

Fixes https://github.com/seanmonstar/warp/issues/377

Allow new Message type `Close` to be created

---

src/filter/service.rs
src/lib.rs

Add more docs around warp::service

---

src/filters/fs.rs

This was caused by `BytesMut::remaining_mut()` returning `usize::MAX` instead of `cap - len`.

Fix `warp::fs` filters that were not reserving the correct read buf size

---

examples/sse_chat.rs

Fix SSE chat example disconnection

---

src/filters/ext.rs
src/filters/ws.rs
tests/ws.rs

This has the side-effect of no longer swallowing PING and PONG frames, and so may effect echo channels, but those are usually just toys anyways.
Closes #368

Fix websocket sending of users' pings

---

tests/fs.rs

Update fs tests due to markdown mime guess change

---

src/filters/log.rs

As discussed in #473 . Let me know if you had something else in mind.

Add request_headers to Log Info

---

src/filters/ws.rs
tests/ws.rs

Allow the max frame size to be set for a websocket

---

src/tls.rs

instead of tokio_rustls::TlsStream
making it available upon instancing instead of after handshake
fixes #514

TlsStream: get remote_addr from AddrStream

---

src/server.rs

Add try_bind_with_graceful_shutdown

---

src/filters/path.rs
tests/path.rs

Fix panic in path::{peek, tail, full} when URI is in authority or asterisk form

---

src/server.rs

cc @seanmonstar @jxs
Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

Add `serve_incoming_with_graceful_shutdown`

---

examples/websockets_chat.rs
src/lib.rs

Closes #578
* Switch to `tokio::RwLock`
* Remove outdated comments
* JS: use `getElementById`, remove behavior that ["will lead to brittle code"](https://html.spec.whatwg.org/#named-access-on-the-window-object)
* JS: show message when disconnected

Clarify websockets chat comments + optimizations

---

src/reply.rs

i think use &hearts; character may be too meaningful;
and the code in the example section of reply.rs can't compiled,

use html heart character and fix compilation problem

---

src/filters/ws.rs

document which websocket messages need handling

---

examples/query_string.rs

fix some typos about query_string example
Signed-off-by: hongliang <513918845@qq.com>

doc: fix some typos about query_string example.

---

src/filters/cors.rs

Motivated by issue #271 and because I faced the same error.

Improve doc for cors allow headers

---

src/filters/cookie.rs
tests/cookie.rs

PR for the issue: https://github.com/seanmonstar/warp/issues/530

making cookie filter generic over T: FromStr + Send + 'static

---

src/test.rs

#611 This fixes the test docs compile error

Fixing test docs with tokio::test

---

src/filter/and.rs
src/filter/and_then.rs
src/filter/mod.rs
src/filter/unify.rs
src/generic.rs

Reduce the amount of IR generated slightly, but mainly cleans them up a bit

Simplify some combinators

---

examples/routing.rs

This PR add route at `/` in routing example as mentioned in https://github.com/seanmonstar/warp/issues/767#issuecomment-752343312

Add route at `/` in routing example

---

src/filters/ws.rs
tests/ws.rs

Add `close_frame` function to `ws::Message`

---

README.md
examples/README.md

- Adds step for newcomers to get running quickly

docs: Add quickstart steps for beginners

---

src/filters/ws.rs
tests/ws.rs

Allow construction of websocket pong messages

---

Cargo.toml
src/filter/mod.rs

I also noticed there was some unnecessary indirection/boxing in the `FilterFn` implementation, so I removed that.

Upgrade tokio-tungstenite to 0.14

---

src/filter/wrap.rs

docs: Add example for wrap_fn()

---

Cargo.toml

Update handlebars in examples to 4.0

Update handlebars to 4.0

---

src/test.rs

docs(tests): Add missing await to Future

---

src/filter/service.rs
src/filters/fs.rs
src/filters/multipart.rs
src/filters/path.rs
src/filters/sse.rs
src/filters/ws.rs
src/reject.rs
src/route.rs
src/test.rs

clippy::from_over_into
clippy::match_like_matches_macro
clippy::needless_borrow
clippy::option_as_ref_deref
clippy::redundant_closure
clippy::single_component_path_imports
clippy::useless_conversion

Fix clippy warnings

---

tests/fs.rs

tests: fix non-existent day in fs tests

---

Cargo.toml
src/filters/ws.rs

The build system I use (antioxidant) hasn't implemented tests yet
and uses a different dependency resolving system,
so best double-check.

Update tungstenite to 0.17.2

---

src/filters/fs.rs

fs: sanitize colons from file requests on windows

---

Cargo.toml
src/filters/multipart.rs

A manual merge of #846, since the conflicts were confusing.
Closes #323 
Closes #1023

use multiparty crate

---

Cargo.toml

Updates pretty_env_logger to 0.5.

Update pretty_env_logger to 0.5

---

src/redirect.rs

Added a description, usage and common use cases for each one of the redirects.

More detailed redirects documentation

---

Cargo.toml
src/tls.rs

https://rustsec.org/advisories/RUSTSEC-2023-0052.html

Update tokio-rustls to 0.24 (Fix RUSTSEC-2023-0052 when "tls" feature enabled)

---

Cargo.toml
src/filters/ws.rs

deps: upgrade tungstenite

---

Cargo.toml
src/tls.rs

deps: update to rustls 0.22

---

Cargo.toml

update to use handlebars v5

---

Cargo.toml

deps: update to rustls 0.23

---

Cargo.toml

Makes futures-channel optional dependency.

deps: make futures-channel optional dependency

---

Cargo.toml
examples/unix_socket.rs

Adds a process to cleanup the unix socket file.

examples: cleanup unix socket file
