README.md

It seems this example doesn't work without specify #[macro_use] and remove warp:: before macro to fix 'non-ident macro paths are experimental'.

Update README.md example to fix example

---

Cargo.toml
src/filters/fs.rs
src/lib.rs
tests/fs.rs

I think hyper already rules out the `Err` branch by validating the whole path earlier.

dir: urldecode route before creating path from it

---

src/filters/query.rs
src/lib.rs
tests/query.rs

A new filter `raw_query()` creates a `Filter` that returns the raw query
string as type String.
- new fn `filters::query::raw_query()`
- expose fn publicly as `warp::raw_query()` in lib.rs
- simple test in `tests/query/rs`

feature: filter for raw query strings

---

examples/websockets.rs
examples/websockets_chat.rs
src/filters/ws.rs
src/lib.rs

add warp::ws2() as a more flexible websocket filter

---

README.md

The information at the repository is too short. While there are more in-depth docs, the README should communicate the purpose of the package.
Currently, it says something like: We have a web framework and we use Filters to do some things.
If it says what are the things the framework does, it could be more easy for newcomers to understand its capabilities.
Also added an explicit link to docs and examples. There are just too many repositories with broken badges, so in my case, I tend to ignore them and look for links in the readme.

Add basic information to README.md

---

examples/returning.rs
src/filter/boxed.rs

This PR adds an example that shows the two main ways to return a filter from a function. It also adds a short example to the `BoxedFilter` docs in case someone stumbles across that before they find `Filter::boxed()`. I don't know whether the redundancy is worth it, but I added the example before I realized that the existing examples were there (since they're not in the docs.rs version yet), so they're in there, but I can also remove them.

Expand documentation on returning filters from functions

---

Cargo.toml

Fixes a long-standing issue with decoding unit enums from query strings

Update serde_urlencoded to 0.5.3

---

src/filters/query.rs
tests/query.rs

If there is optional query parameters to a handler, treat an URL with no question mark as equal to an URL that ends in a question mark.  Technically, the URL ending in a question mark has an empty query string while the URL without a question mark has no query string, but in practice, it should not make any difference and the question mark is rarely present.
If there are required query parameters, I don't think this makes any difference either, as extracting them from an empty string will fail fast (and the fail should behave the same with or without that question mark anyway).
This fixes #86 in the place where it is easy to fix.  Also added a bunch of tests for missing query strings (and query string missing required pieces).

Treat no query string as empty query string

---

.gitignore
src/filters/cookie.rs

An additional cookie filter that I needed to implement inside the warp crate because the necessary building blocks, such as header::optional_value are only crate-public.
Rather than accepting this PR, I guess it will be more helpful to understand what you mid-term goal is to support writing own headers (which I think will be a very common thing to do).

Add optional cookie value filter

---

Cargo.toml
src/filters/fs.rs
src/lib.rs

This pull request sets the last-modified header when serving responses from the file system.
This implementation uses [httpdate](https://github.com/pyfisch/httpdate) to format the date.
It appears that Hyper uses the deprecated [time](https://github.com/rust-lang-deprecated/time) crate; which is also an option.

Add last-modified header to file and dir filters (#45)

---

src/reply.rs

Previously referred to headers; should refer to status codes.

Fix typo in `with_status` documentation

---

Cargo.toml
examples/errors.rs
examples/futures.rs
examples/todos.rs
src/filter/mod.rs
src/filters/body.rs
src/filters/cookie.rs
src/filters/fs.rs
src/filters/header.rs
src/filters/path.rs
src/filters/query.rs
src/lib.rs
src/reject.rs
src/reply.rs
src/server.rs
src/test.rs
tests/body.rs
tests/cookie.rs
tests/fs.rs
tests/header.rs
tests/method.rs
tests/query.rs

The `Rejection` type can now nest and combine arbitrary rejections,
so it is no longer bound to a small set of meanings. The ranking of
status codes is still used to determine which rejection gets priority.
A different priority can be implemented by handling rejections with
a `Filter::recover`, and searching for causes in order via
`Rejection::find_cause`.
- Adds `warp::reject::custom()` to create a `Rejection` with
any `Into<Box<std::error::Error>>`. These rejections should be
handled with an eventual `Filter::recover`. Any unhandled
custom rejections are considered a server error.
- Deprecates `Rejection::with`. Use custom rejections instead.
- Deprecates `Rejection::into_cause`, as it can no longer work. Always
returns `Err(Rejection)`.
- Deprecates `Rejection::json`, since the format …

rework Rejection system

---

src/filter/service.rs
src/filters/addr.rs
src/filters/mod.rs
src/lib.rs
src/route.rs
src/server.rs
src/test.rs
src/tls.rs
src/transport.rs

Returns the socket address of the immediate connection, if the transport
type supports socket addresses.
Closes #9

Add  `warp::addr::remote()` filter.

---

examples/sse.rs
examples/sse_chat.rs
src/filters/mod.rs
src/filters/sse.rs
src/lib.rs
src/sse.rs

Helps turning server events stream into *SSE* reply.
If it's not reasonable to merge this functionality with warp,
I would like to create different crate but I have some troubles with it.

Server-sent events for warp

---

src/filters/ws.rs

Tungstenite's `Message` implements `Clone`, but the wrapper in Warp does not. You don't run into this in your websocket chat example because you run the Message through Display first, and clone the string.

Replicate traits from protocol::Message on Message

---

src/reject.rs
src/reply.rs

what it says on the tin.
tbh, would it make sense to `impl<T: Into<hyper::Body>> ReplySealed for T`?

impls ReplySealed for Vec<u8> and &'static [u8].

---

README.md

I noticed the code snippet in the readme doesn't compile currently, this small update fixes it.

Update code snippet in readme

---

src/reply.rs

Hi, thanks for the great warp lib!
I think it is useful if the enum Cow which represents string implements Reply(Sealed).
In my case, it is especially nice when using the with_status method to make a impl Reply like a WithStatus.
If the Cow implements Reply, Error(assume enum) which has some static str, String, or Cow, and which is underlying a Rejection can provide first argument of the method without unnecessary allocation.
I implemented it by using existing impl for static str and String.

impls ReplySealed for Cow<'static, str>.

---

Cargo.toml

This change solves the following dependency conflict when using reqwest `0.9` with warp `0.1`.
```
error: failed to select a version for `ring`.
... required by package `rustls v0.14.0`
... which is depended on by `warp v0.1.14`
... which is depended on by `my-crate v0.1.0 (/home/joshua/Projects/my-crate)`
versions that meet the requirements `^0.13.2` are: 0.13.5
the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.14.6`
... which is depended on by `rustls v0.15.1`
... which is depended on by `tokio-rustls v0.9.1`
... which is depended on by `hyper-rustls v0.16.1`
... which is depended on by `reqwest v0.9.12`
... which is depended on by `my-crate v0.1.0 (/home/joshua/Projects/my-crate)`
```

Update rustls to avoid conflict with reqwest

---

src/filters/fs.rs
tests/fs.rs

According to RFC 7232, 304 Not Modified responses should not generate representation metadata other than the following fields: Cache-Control, Content-Location, Date, ETag, Expires, and Vary.
This avoids a warning from hyper when logging is enabled: "content-length value found, but empty body provided". While it is allowed to provide Content-Length for Not Modified responses it is unnecessary.

Skip headers for Not Modified fs responses

---

examples/sse_chat.rs
src/filters/sse.rs

The keep_alive() function returns a builder to allow customizing the
interval and content of keep-alive SSE messages. Adjusts the work in #206.
Closes #206 
Closes #204

Add warp::sse::keep_alive() to replace keep()

---

examples/errors.rs
src/filters/cookie.rs
src/filters/header.rs
src/filters/query.rs
src/filters/sse.rs
src/reject.rs

I'm mostly looking for feedback, this is more a proof of concept rather than the actual solution.
I'm trying to render rejections as a JSON object. For custom errors, it already works totally fine. However, in order to reuse all the existing `Filter` implementations, while being able to capture the actual reason in a custom `recover` function, I felt it was needed to define a few of the existing error types as `pub`.
Btw, everything's awesome, thanks for `warp` :cyclone:

Expose more basic internal HTTP error types

---

src/server.rs

This introduces two bind methods which do not panic in case we fail to bind.
Some feedback would be appreciated.
I found it a bit awkward to integrate with the existing set of macros without doing a bigger rewrite. The signature of `try_bind_ephemeral` immediately returns a `Result`, but could be written to return a future which resolves to a Future. But this seems a bit overkill though given that it's not actually an async operation and any consumer of the API can trivially make it into a future using e.g. `futures::future::result`.
Related: #237

Introduce try_bind/try_bind_ephemeral as fallible bind methods

---

Cargo.toml
src/error.rs
src/filters/body.rs
src/filters/mod.rs
src/filters/multipart.rs
src/lib.rs
tests/multipart.rs

This provides initial `multipart/form-data` support. This is more just a raw interface, providing a `Stream` of `Part`s that are in turn `Stream`s of bytes. The internal implementation isn't optimized, just holding the full form in memory, but is exposed as `Stream`s to allow for streaming support to be added later.
Closes #40

Add warp::multipart::form filter

---

CHANGELOG.md
Cargo.toml
src/filters/fs.rs
src/lib.rs

This helps avoid duplicating crates in https://bugzilla.mozilla.org/show_bug.cgi?id=1568540

Update tungstenite and serde_urlencoded

---

examples/todos.rs

Previously, none of the examples used query parameters.

Add query parameters to the todos example.

---

src/filters/cors.rs
tests/cors.rs

Using the cors filter in conjunction with the log filter resulted in a compilation error as the Clone trait was not satisfied for `cors::internal::CorsFilter`. This is a naive attempt to fix it by
deriving Clone.
* derive Clone on CorsFilter
* introduce regression test for cors with log filter
***
Also provided a minimal case that fails over [here](https://github.com/xla/warp-cors-log-testcase) with the error in the README.

Fix cors filter in conjunction with log filter

---

src/filters/ws.rs

Until now the API only allowed getting a reference. For code wanting to work on websocket connections, regardless of whether they're provided by warp, tungstenite, tokio-tungstenite or other websocket libraries this is a problem because the type from warp has to be kept all the way through algorithms to avoid making a needless copy of all the data.
This adds a new method to `warp::ws::Message` called `into_bytes` which will return a `Vec<u8>` of the inner data.
Note that this alleviates this problem for code wanting to operate on binary messages. However, there could and probably should also be a a similar method to extract string messages without copying.
I chose to delegate the call to the inner tungstenite message because I feel tungstenite has [better …

Allow extracting the binary data out of a ws::Message without copying.

---

src/filters/cors.rs

Adds an example of usage of `allow_any_origin()` in the docs.

Adds example in docs with cors `allow_any_origin()`

---

src/filters/ws.rs

This (very small) PR adds the ability to send WebSocket `Ping` messages. This functionality is built into Tungstenite, but was not previously exposed in Warp's public API.
The idea behind this PR is to support the use-case described in #269.  Ultimately, it would be helpful for Warp to expose functionality that automates sending of pings (to parallel the SSE `keep_alive` method).  This PR doesn't achieve that, but lays the foundation for future work along those lines and, in the meantime allows users to manually send pings (for example, one can use this PR with a timer/loop to achieve a keep-alive ping slightly more verbosely).

Add ability to send Ping ws Messages

---

src/filters/path.rs
src/lib.rs

When using `file:` URLs to visit the docs, links like `[filters](filters)` bring
up a directory listing, even though they do work on docs.rs.

Fix a few minor typos.

---

examples/README.md
examples/routing.rs
examples/todos.rs
src/filters/path.rs

While switching Interledger.rs to `warp`, we made two subtle and hard-to-debug mistakes:
- failing to include the `warp::path::end()` filter and thus having a shorter route like `/math` accidentally match a request for a longer path like `/math/sum/:u32/:u32`
- putting auth checks before the path-related filters and winding up with auth-related errors when a request for a completely different route had an invalid body
This attempts to document those two issues in the rustdoc and examples, though there are probably some other places this type of gotcha could be documented.
This also includes a README for the `examples` directory to point newcomers to the examples in a specific order.

Better document two foot-guns

---

src/reject.rs

Is the [link to the `recover` filter](https://github.com/seanmonstar/warp/blob/0828822e834d6837091813ad3efe2a03a17d0da7/src/reject.rs#L143) on the [reject::custom](https://docs.rs/warp/0.1.20/warp/reject/fn.custom.html) page moving up one directory too many?
On my browser the path resolves to https://docs.rs/warp/0.1.20/trait.Filter.html#method.recover which doesn't lead anywhere useful. If I change `warp/0.1.20/` to `warp/0.1.20/warp`, then it seems to work:
https://docs.rs/warp/0.1.20/warp/trait.Filter.html#method.recover.

Fix broken link in reject::custom docs

---

src/filter/mod.rs
src/filters/path.rs
tests/filter.rs

Technically a breaking change, but in practice, the other only error
type is `Never`, and so `warp::any().or_else(..)` didn't make sense.

Alter Filter::{or, or_else, recover} to require Self::Error=Rejection

---

examples/dyn_reply.rs
src/reply.rs

Implement Reply for Box<dyn Reply>

---

src/lib.rs
src/redirect.rs

This just adds `warp::temporary_redirect` (307) alongside `warp::redirect` (301). Found this utility function helpful and figured others might need it too. 
In my case I was implementing oauth login and needed code to run in the handler before every redirect. A permanent redirect (301) gets cached in most browsers so `warp::redirect` wouldn't work because the server would never even get called on subsequent login attempts.

add warp::temporary_redirect

---

src/lib.rs

mildly annoying to have to also depend on hyper for hyper::Body; already re-exports http, so might as well do both

Re-export hyper

---

examples/unix_socket.rs

Once we're on Tokio 0.2.0, this example also needs the `uds` feature on Tokio.

Adds example for Unix sockets. Resolves #282.

---

Cargo.toml
examples/futures.rs
examples/sse.rs
examples/sse_chat.rs
examples/websockets_chat.rs
src/filters/body.rs
src/filters/cors.rs
src/filters/fs.rs
src/filters/log.rs
src/filters/multipart.rs
src/filters/reply.rs
src/filters/sse.rs
src/filters/ws.rs
src/lib.rs
src/redirect.rs
src/reject.rs
src/reply.rs
src/server.rs
src/test.rs
tests/fs.rs
tests/ws.rs

I got rid of a few `'static` bounds from server.rs to get the `unix_socket` example builduing, but it seems like most of the others are unnecessary as well?

Update to hyper 0.13/tokio 0.2

---

examples/handlebars_template.rs
src/filters/body.rs
src/filters/cors.rs
src/filters/ext.rs
src/filters/sse.rs
src/reject.rs
src/reply.rs

Rust is about to deprecate `Error::description` for real, and warp is one of the crates broken by that change.

Remove deprecated Error::description

---

examples/sse.rs
examples/sse_chat.rs
src/filters/sse.rs
src/lib.rs

- Removes the `warp::sse()` filter that yields an `Sse` type.
- Adds `warp::sse::reply` that does the same as what the `Sse::reply`
method did.

Change Server-Sent Events API

---

examples/sse_chat.rs
src/filters/body.rs
src/filters/multipart.rs
tests/body.rs

- Adds `warp::body::bytes` to concatenate into a single `Bytes`.
- Adds `warp::body::aggregate` to aggregate into some `impl Buf` without
copying data.
- Changes `warp::body::stream` to yield an `impl Stream`.
- Removes `warp::body::concat`.
- Removes `warp::body::BodyStream`.
- Removes `warp::body::StreamBuf`.
- Removes `warp::body::FullBody`.

Change a few `warp::body` filters

---

src/filters/path.rs
tests/path.rs

This makes `path!("foo" / "bar")` include an `end()` filter by default, while providing support for `path!("foo" / "bar" / ..)` to signal a prefix.
Closes #357

Change path macro to assume end by default

---

src/filters/ws.rs
tests/ws.rs

Currently  using `as_bytes` panics in some cases. This patch handles all cases, by returning an option that is `Some` if the message contains a payload, and `None` if not.
Alternatively, this PR could be changed so that `Ping` and `Pong` messages also returned `None`, if preferred.
This requires changing the signature from `&[u8]` to `Option<&[u8]>`.

Remove panic branch in `Message::as_bytes`.

---

src/filter/mod.rs
src/filter/or.rs
src/filter/or_else.rs
src/filter/recover.rs
tests/filter.rs
tests/path.rs

I noticed that `or_else` and `recover` could conceivably be infallible (handle all error cases), but that couldn't be expressed in the type system, since they *required* the functions to return `Result<_, Rejection>`.
This allows `or_else` and `recover` combinators to be clearer about whether they too can reject, and also allows the compiler to better optimize if they handle all rejections.
This can disrupt type inference, so it's a breaking change, and needs to get in before the 0.2 release.

Allow or_else and recover to return infallible futures

---

examples/dyn_reply.rs

The cast is not needed anymore as https://github.com/rust-lang/rust/issues/60424 has been fixed.

chore: remove cast from example

---

src/lib.rs

Currently this links to https://docs.rs/warp/0.2.1/warp/reject which does not exist.

Attempt to fix broken link to https://docs.rs/warp/0.2.1/warp/reject

---

src/filters/fs.rs
src/reject.rs

- Return 404 Not Found for NotFound
- Return 403 Forbidden for PermissionDenied
- Return 500 Internal Server Error for other errors

Adjust `warp::fs` rejections depending on File::open error kind

---

src/test.rs

New to warp and reading the docs, the asserts here seem to apply to the math() filter.

'Reply' example is testing the math() filter

---

Cargo.toml
examples/rejections.rs
examples/sse_chat.rs
src/filters/body.rs
src/filters/fs.rs
src/filters/ws.rs
src/test.rs
tests/filter.rs

I tried to add support for `tokio-tungstenite` in the websocket filter. The only difference in the internal api is that `WebSocket::from_raw_websocket` now returns a Future.
The main problem right now is that the `tokio-tungstenite` dependency is from the github repository  because the version on crates.io uses futures v1.
Edit: Reference #366

Websocket filter with tokio-tungstenite

---

examples/websockets_chat.rs

and use async/await constructs

update websockets chat to use tokio Mutex instead of std 

---

Cargo.toml
src/tls.rs

[`tokio_rustls::server::TlsStream`](https://docs.rs/tokio-rustls/0.12.2/tokio_rustls/server/struct.TlsStream.html) doesn't expose constructor methods, the public entrypoint is TlsAcceptor which has [`accept`](https://docs.rs/tokio-rustls/0.12.2/tokio_rustls/struct.TlsAcceptor.html#method.accept) that returns [`Accept`](https://docs.rs/tokio-rustls/0.12.2/tokio_rustls/struct.Accept.html) which impls `Future`.
The way i found to get around it was implementing AsyncRead/AsyncWrite on a wrapper `TlsStream` that handshakes `Accept` first. 
I tried first handshaking on `warp::tls::TlsAcceptor` but on errors `Hyper` server would stop

switch rustls for tokio-rustls

---

src/reply.rs

We had a case where we were boxing up replies, and needed them to impl `Send + Sync` to use in other code. `Box<dyn Reply + Send + Sync>` unfortunately doesn't implement `Reply`, because the impl is too specific. This generalizes the impl of `Reply` to include any `Box<T>` where `T: Reply + ?Sized`.

Generalize Reply impl for Box<dyn Reply>

---

src/reject.rs

Add a name method to `MissingHeader`, `InvalidHeader` and
`MissingCookie` that allow access to their internal name field. This is
useful when recovering from rejections and down-casting to return
specific replies for cases where additional information should be sent
to the client.
Resolves https://github.com/seanmonstar/warp/issues/440

Add method to expose missing/invalid reject names

---

src/filters/ws.rs
tests/ws.rs

We had a problem in production with an overly large websocket message from chrome not being received in a warp based service. To solve this, we had to fork warp and allow the max_frame_size to be set.
We are using 0.1.x in this system, but if this is accepted we could also do an additional PR against master.

Allow the max frame size to be set for a websocket

---

.github/workflows/ci.yml
Cargo.toml
README.md
examples/compression.rs
examples/file.rs
src/filters/compression.rs
src/filters/mod.rs
src/lib.rs

This PR adds compression filters to Warp, using the [`async-compression`](https://docs.rs/async-compression/0.3.1/async_compression/) crate. Compression is implemented by utilizing the fact that [`Body`](https://docs.rs/hyper/0.13.3/hyper/struct.Body.html) implements [`Stream`](https://docs.rs/futures/0.3.4/futures/stream/trait.Stream.html), and with a little bit of massaging we wrap the Response body in an encoder, and then create a new Body from that.
This implementation is definitely an MVP, there are two pitfalls a developer could fall into with this implementation
1. We don't check the `accept-encoding` header before compressing the Body, this could lead to some responses being invalid.
2. A user could theoretically double compress a response, leading to invalid responses.
From here …

Add Compression Filters

---

src/test.rs
tests/addr.rs

Support setting the remote addr in the test request builder.
Leverage this functionality to validate the `warp::addr::remote` filter
works as intended.

Set Remote Addr for Test Request Builder

---

tests/query.rs

I couldn't find documentation on how to parse key only query parameters. I added a unit test to see how they would behave and I believe this adds some documentation benefit, so I'm sending a pull request.

Add test for name-only query parameters.

---

examples/autoreload.rs

This example show how to use systemfd in a routes with closure and avoid the error
```rust
--> src/main.rs:10:1
|
10 | #[tokio::main]
| ^^^^^^^^^^^^^^
| |
| captured outer variable
| move occurs because `svc` has type `warp::filter::service::FilteredService<warp::filter::or::Or<warp::filter::and::And<impl warp::Filter+std::marker::Copy, impl warp::filter::FilterClone>, warp::filter::and::And<impl warp::Filter+std::marker::Copy, impl warp::filter::FilterClone>>>`, which does not implement the `Copy` trait
| move out of `svc` occurs here
| move occurs due to use in generator
```

update example with more complex routes

---

src/filters/compression.rs

The Content-Length header should represent the length of the compressed data, which we can't compute ahead of time for streamed bodies.
[The header is set when using the `dir` filter](https://github.com/seanmonstar/warp/blob/master/src/filters/fs.rs#L305), which means that combining the `dir` and `compression::*` filters will result in invalid responses. In my case, this caused some JavaScript files to be non-deterministically erroneously loaded in Chrome. `curl` also complains:
```
curl: (18) transfer closed with 3614 bytes remaining to read
```
I don't think this is the best implementation, but it is probably the simplest. A better way to do this would be to differentiate between sized and non-sized bodies later down the pipeline and only add the Content-Length header when …

Remove Content-Length header when using a compression filter

---

src/reply.rs

This should allow better `and_then()` composition using warp::reply::html() as was discussed on the tokio Discord.

html() now returns the Html struct instead of impl Reply

---

Cargo.toml

Warp is an outlier in our dependency tree with its older version of tokio-rustls.
This update was trivial and passes `cargo test --all-features`.

Update to tokio-rustls 0.13.1

---

Cargo.toml
src/filter/and.rs
src/filter/and_then.rs
src/filter/or.rs
src/filter/or_else.rs
src/filter/recover.rs

pin-project will deprecate the project attribute due to some unfixable
limitations.
Refs: https://github.com/taiki-e/pin-project/issues/225
*Although the deprecation of the project attribute has not been released yet, this PR is submitted in advance to avoid the CI from being broken by deprecated warnings.*

Remove uses of pin_project::project attribute

---

examples/rejections.rs
src/filters/body.rs

PR for the issue #650 
Adds a `.cause()` method for `BodyDeserializeError`, so the underlying cause can be used to handle the error properly.
Also adds a small update to the `rejections.rs` example to showcase it.

Add Cause for BodyDeserializeError and update Rejections example

---

src/filters/fs.rs

#648 requires a way to retrieve the file path from a `File` reply. This PR implements such a getter by storing the `ArcPath` in the `File` struct and providing a reference to it. The documentation shows an example use-case where the `Content-Type` header is changed based on the filename.

Add path getter for File Reply

---

src/filters/ws.rs

Addresses #653. Given that other `Known` rejections are public, `MissingConnectionUpgrade` should be as well.

Make MissingConnectionUpgrade public 

---

Cargo.toml
src/filter/service.rs
src/filters/body.rs
src/filters/cors.rs
src/filters/fs.rs
src/filters/header.rs
src/filters/method.rs
src/filters/path.rs
src/filters/query.rs
src/filters/sse.rs
src/filters/ws.rs
src/reject.rs
src/reply.rs
src/server.rs
src/test.rs

The `tracing` crate and related libraries provide an interface for Rust
libraries and applications to emit and consume structured, contextual,
and async-aware diagnostic information.  `tracing` is maintained by the
Tokio project and is becoming widely adopted by other libraries in the
stack Warp uses, such as [`hyper`], [`h2`], and [`tonic`] and in [other]
[parts] of the broader Rust ecosystem.
[`tracing` crate]: https://github.com/tokio-rs/tracing
[`hyper`]: https://github.com/hyperium/hyper/pull/2204
[`h2`]: https://github.com/hyperium/h2/pull/475
[`tonic`]: https://github.com/hyperium/tonic/blob/570c606397e47406ec148fe1763586e87a8f5298/tonic/Cargo.toml#L48
[other]: https://github.com/rust-lang/chalk/pull/525
[parts]: https://github.com/rust-lang/compiler-team/issues/331
Tracing …

Migrate internal diagnostics to `tracing`

---

src/filters/path.rs
src/filters/trace.rs

The headers can frequently contain sensitive info, so for now we shouldn't emit traces that might log this data accidentally.

Remove headers from default tracing spans

---

src/filters/sse.rs

As the `Sync` requirement on `Body::wrap_stream` was removed in https://github.com/hyperium/hyper/pull/2187, it can now also be removed on the stream passed to `warp::sse::reply`.

Remove `Sync` restriction on stream bassed into `warp::sse::reply`

---

src/server.rs

Closes #666 
This PR started by just removing some `'static` bounds on the `addr` arguments of some functions in `server.rs`.
While I was there I also relaxed some of the other arguments' lifetimes by adding an explicit lifetime to the returned type. I'm not yet sure if this was a wise idea. I don't believe its a breaking change as presumably all the current callers are providing `'static` arguments so their returned lifetime will still be `'static`. I might be wrong here though.
This is also my first PR, so let me know if I've missed anything obvious.

Relax some lifetime bounds

---

Cargo.toml

Fix #694 
It works well in my environment.
But when other user mixes use tokio-tungstenite v0.10 and v0.11, there will be compatibility issues.
ps: upgrade to the same version can solve this problem

Upgrade dependence

---

examples/handlebars_template.rs
src/filters/path.rs
src/route.rs
tests/fs.rs
tests/path.rs

return from set_unmatched_path on malformed path, closes #568 and #460, backport to 0.1.x

Backport of tail crash fix #568 (#697) to 0.1.x

---

Cargo.toml
src/filters/fs.rs

`percent-encoding` is already pulled in with the `url` & `serde_urlencoded` crates.
And `serde_urlencoded` v0.7 switched to `ryu` like `serde_json` did in the past.

Reduce number of dependencies: Switch to percent-encoding & update serde_urlencoded

---

src/server.rs
src/tls.rs

OCSP isn't widely supported yet in rust TLS land (e.g. creating requests/responses) but rustls provides the stapling mechanism—you can supply a chunk of bytes, which is presumed to be a valid DER response, which is passed verbatim to the client.
In an ideal world this would become more fully featured:
* automatic fetching and caching of the OCSP response
* updating the response without having to restart the server, since any token is usually only valid for 7 days.
However the barebones/static version of this is useful to me and I would like to simply expose the rustls config.

Permit stapling an OCSP response when using TLS

---

src/test.rs
tests/ws.rs

Right now query string is ignored when using `warp::test::ws()`. This change will allow to pass query parameters to the test websocket.

Allow passing query parameters to the test websocket

---

src/reject.rs

This allows the `?` operator to easily be used from within functions without `map_err`.

Add From<Reject> for Rejection.

---

src/filters/multipart.rs

I found typo on multipart doc. I think this is a quick fix

Fixing typo on multipart docs

---

src/server.rs
src/tls.rs

This extends the `TlsServer` for optional client authentication by providing `client_auth_optional()` and `client_auth_required()` method (and their `_path()` counterparts) to expose `rustls` functionality, partly addressing #504.
It seems that others are having the same request/issue as well (#737), but this pr implements tls client authentication along the lines of the existing tls server authentication (`cert()` and `key()` methods) in contrast to #739.

Tls client authentication

---

src/filters/cors.rs

fixes https://github.com/seanmonstar/warp/issues/754

replaces "instead" with "intend" in allow_any_origin comments

---

examples/sse.rs
examples/sse_chat.rs
src/filters/sse.rs

rework sse filter

---

README.md

Update the README example to use Tokio 1.0 and Warp 0.3, as mentioned
[here](https://github.com/seanmonstar/warp/pull/777#issuecomment-761527432).

Update README for 0.3 release

---

src/filters/cors.rs
tests/cors.rs

The current implementation does not correctly interpret the `Access-Control-Request-Headers` value in a CORS preflight if it includes spaces.
For example, if
* warp cors is configured with `.allow_headers([header::AUTHORIZATION, header::CONTENT_LENGTH])` and
* preflight request includes `Access-Control-Request-Headers: content-length, authorization`,
then the preflight request will be rejected (HTTP 403) because the header value is split on ",", and `" authorization"` (note the space!) is not in the list of allowed headers.
This PR adds a `.trim()` to the parsing process to allow for spaces in `Access-Control-Request-Headers` header values. It tweaks a test so that it fails without this PR's fix.
Technically, the standard prescribes that `Access-Control-Request-Headers` values should …

Fix: CORS: Allow spaces in Access-Control-Request-Headers values

---

Cargo.toml
src/filters/trace.rs
src/server.rs

The `tracing-futures` dependency is no longer needed since `tracing` v0.1.21

Remove the obsolent tracing-futures dependency

---

src/redirect.rs
tests/redirect.rs

The 303 is like the existing 307 except it forces the GET HTTP method. The 308 is like the existing 301 except it reuses the HTTP method and body for the new location.

Add 303 and 308 redirect helpers

---

src/filters/fs.rs
tests/fs.rs

This fix originates from #815. 
This fixes the edge case where  the bound == file size. 
By default the bound is always incremented by one
but if it is equal to the file size it should *not* increment.

filters: fs: end range parameter edge case

---

src/error.rs

Without this it's hard to figure out in code what's the real reason for
the failure. Parsing the description is not enough.

Add error source implementation

---

src/filters/fs.rs

This is a fix for feature request #834

Allow HEAD requests to be served by fs::dir() filter

---

examples/unix_socket.rs

It wasn’t possible to run the tests on Windows without this change, as the examples have to be compiled too:
```
> cargo test -- form_fields
Compiling warp v0.3.1 (D:\Media\src\warp)
error[E0432]: unresolved import `tokio::net::UnixListener`
--> examples\unix_socket.rs:3:5
|
3 | use tokio::net::UnixListener;
|     ^^^^^^^^^^^^------------
|     |           |
|     |           help: a similar name exists in the module: `TcpListener`
|     no `UnixListener` in `net`
error[E0432]: unresolved import `tokio_stream::wrappers::UnixListenerStream`
--> examples\unix_socket.rs:4:5
|
4 | use tokio_stream::wrappers::UnixListenerStream;
|     ^^^^^^^^^^^^^^^^^^^^^^^^------------------
|     |                       |
|     |                       help: a similar name exists in the module: …
```

Let `unix_socket` example compile but not run on Windows

---

src/filters/query.rs

docs: Add examples to query

---

Cargo.toml

The main advantage of its 0.18 release is that it uses rand 0.8, not 0.7. I was inspired to open this PR because my project (which uses warp) is pulling in both rand 0.8 (directly) and 0.7 (by way of warp, by way of multipart).
Multipart's MSRV is now 1.36, I couldn't see a MSRV for warp, but if the MSRV conflicts with warp's then please decline this PR :)

Upgrade to multipart 0.18

---

examples/websockets_chat.rs

Hi, thanks for maintaining this great library. I think there is a line in the `websockets_chat.rs` library to clone an `Arc<_>` that isn't necessary, since the `users` variable is only passed around by a reference of type `&Arc<_>` anyway. I removed this cloned variable, and it still seems to compile and run fine.
Let me know if this makes sense.

Remove unnecessary clone in `websockets_chat.rs`

---

Cargo.toml

[`log::Record`](https://docs.rs/log/0.4.14/log/struct.Record.html)'s are `!Send + !Sync` and `tracing`'s `log` feature automatically uses those, which can be problematic for consumers. Exposing the feature allows consumers to not enable the `log` feature.
The feature is called `trace-log` since both `log` and `tracing-log` are blocked by crates with the same name.

Expose tracing/log feature

---

Cargo.toml

https://stackoverflow.com/questions/67107901/disable-http2-in-seanmonstar-warp

Reexport http2 feature

---

src/filters/ws.rs

It's super confusing, that we should manually poll rx part of the socket to make pings handled automatically.

Add docs for ping handling

---

src/filters/path.rs
src/server.rs

The documentation for most of the warp::Server methods (bind,
try_bind_with_graceful_shutdown, etc) indicate that the futures
they return can be run on any runtime. However, these functions
panic if they are called outside the context of a Tokio 1.x runtime.
This commit makes a minor update to the documentation to note that
these function return futures that run on the /current/ runtime.
Note that try_bind can actually be called outside the context of a
Tokio runtime, so the docstring for that method remains unchanged.

docs: Note that most futures from Server run on current runtime

---

src/filters/compression.rs

This PR just does a small upgrade of [`Poll::map_err`](https://doc.rust-lang.org/std/task/enum.Poll.html#method.map_err-1) which is stabilized since 1.51.0.
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1510-2021-03-25

Use stabilized `Poll::map_err` on compression filter stream

---

src/reject.rs

I saw an easy open issue #126 to expand the docs about handling rejections. I'm new to the library but would like to get involved with the project.

expanded documentation on how to handle rejections

---

Cargo.toml

Hi, thanks for maintaining this great project!
The tokio-tungstenite library was recently updated to version 0.15 which includes some performance improvements over version 0.14. In my test setup, which uses "websocat" to send messages to the bundled example echo-server ("examples/websocket.rs"), the throughput with version 0.15 is improved from about 60 MB/s to 80MB/s with a single connection.
Using several parallel connections maxes out the network bandwidth so the total transfer time is about the same, but the CPU load on the server is consistently lower (~50% CPU idle according to "top" with tokio-tungstenite 0.15, compared to ~35% idle with version 0.14). The echo-server was run on a Raspberry Pi 4 with the standard Raspberry Pi OS.
I thought it might be worthwhile to update to this …

Upgrade tokio-tungstenite to 0.15

---

examples/websockets_chat.rs

When I used the websockets example, I found myself wondering why you need to `send(Ok(Message...))` rather than `send(Message...)`. It turns out [`stream.forward()` is only implemented on `TryStreamExt`](https://github.com/rust-lang/futures-rs/issues/2004).
So I rewrote the example to use `send()` which avoids the unnecessary `Result`.

Simplify websockets_chat example to avoid unnecessary `Result`.

---

src/redirect.rs
tests/redirect.rs

This adds a `302 Found` redirect helper 😉

Add 302 redirect helper

---

examples/README.md
examples/custom_methods.rs

Fixes #871.
This has been created as a result out of #874.

Add example how to use custom HTTP methods

---

src/filter/mod.rs
src/filter/then.rs

Tipping point for me to jump into `Future` type hell to implement this was [this](https://github.com/seanmonstar/warp/issues/712#issuecomment-697031645) comment - but I'd say it's worth it. I've used it in my personal project for a while, and the code I've been able to write is much cleaner, I think.
Changes:
- Added `Filter::then()` and complementary type `Then`. Exactly like `map`, but async. The name is meant to reflect [future's `then()`](https://docs.rs/futures/0.3.17/futures/future/trait.FutureExt.html#method.then) function.
- `Filter::and_then()` documentation now points to `Filter::then()` as an alternative, since my understanding is that:
> Rejections are meant to say "this filter didn't accept the request, maybe another can." 
Fix #712
Fix #594
Providing Reply implementations …

Implemented `Filter::then`

---

examples/tls.rs

It was clear that I didn't need the `#[cfg(feature ...)]` in order to get
a `Server` that could respond to `.tls()`, but I wasn't immediately sure if
just adding the tls feature to the warp dependency (in Cargo.toml) was
enough, or I had to specify some transitive dependency with it, or
something else. And as the feature wasn't enabled, the docs produced
with `cargo doc --workspace` didn't include `Server.tls`, so I started to
question if the example I was looking at even matched the warp version
I was working with.
Eventually I just tried adding it to the warp dep and it (of course)
just worked, but for the sake of others I reckon a more explicit
pointing in the right direction could be helpful.

Document tls example with compilation instruction

---

Cargo.toml
src/test.rs
tests/ws.rs

This implements `Sink` and `Stream` for `WsClient`.
If you use `tokio-tungstenite` as your websocket client, you will usually have a `tokio-tungstenite::WebSocketStream` to work with, which exclusively uses the `Sink` and `Stream` traits for sending and receiving messages. Implementing `Sink` and `Stream` for `WsClient` as well allows for writing code that works with both the real `tokio-tungstenite::WebSocketStream` and `WsClient` by relying only on the `Sink` and `Stream` traits in the implementation, especially if you combine it with #903 which provides conversions between `warp::ws::Message` and `tungstenite::protocol::Message`.
Initially I tried to implement this using the tokio mpsc channels that `WsClient` was using, but found it to be impossible.
Implementing `Stream` isn't an …

Implement Sink and Stream for WsClient

---

Cargo.toml
src/filters/compression.rs
src/filters/mod.rs

Hello there! This PR splits the `compression` feature into two: `compression-brotli` (Brotli) and `compression-gzip` (Deflate and Gzip). As their names suggest, each feature is responsible for enabling support for their respective compression algorithms.
This is done in an effort to minimize the `cargo tree` for those who do not intend to use one or the other. Allowing the `warp` consumer to choose which compression algorithms to support gives finer-grained control over their dependencies, which is nice!
The `async-compression` crate pulls in the `brotli` crate when that feature is enabled. Similarly, it pulls in the `flate2` crate when the `deflate` feature or the `gzip` feature is enabled. Observe that the `deflate` and `gzip` features have been merged as the `compression-gzip` feature …

Feat: split compression features for Gzip and Brotli support

---

Cargo.toml
src/reject.rs
src/tls.rs

This change bumps the tokio-rustls version to pick up the new version of
rustls.
This helps to avoid duplicate dependencies when using other libraries
that depend on rustls.

Update tokio-rustls to v0.23

---

Cargo.toml

Hello everybody
warp is curently using tokio-util 0.6 in february tokio-util 0.7 was released.
The changelog can be found here [here](https://github.com/tokio-rs/tokio/blob/master/tokio-util/CHANGELOG.md).
In my opinion this should cause no breakage in warp and would reduce duplicate dependencies in my project.
warp uses hyper which in turn uses h2, h2 already updated to tokio-util 0.7 in this [commit](https://github.com/hyperium/h2/commit/a54d9265b7a6dfc78f67c38db62bfbeae790c1f8).
It would probably make sense to also create a pull request for hyper (which I could do).
I just ran `cargo test` to make sure everything works, as I could not find further instructions for testing.
Help and input would be appreciated!
Kind regards

Update tokio-util to 0.7

---

src/filters/trace.rs

Currently, the `warp::trace()` filter assumes that:
- Ok response from filter => INFO / "finished processing with success"
- Err / rejection from filter => ERROR / "unable to process request" (5xx); or WARN / "unable to serve request" (4xx)
However, this doesn't work well with custom rejections:
Normally you will `.recover()` the rejection and return a 4xx/5xx reply. `warp::trace()` will currently log INFO / "finished processing with success", as if everything is OK, whereas it should log WARN/ERROR, same as for known rejections.
This PR changes the logging to be based only on the status code.

Use status code for trace filter log level / message.

---

src/test.rs

Comment says "Or simply test if a request matches (doesn't reject)"
therefore I would expect for assert to test for success. Also this
example (for sum) will always match. It's confusing the code example
actually tests if it doesn't match.

Fix test example so it doesn't fail

---

examples/todos.rs
tests/ws.rs

🧹 Fix todos example  and ws test compilation error
- Per Sean McArthur's suggestion here - https://github.com/seanmonstar/warp/pull/1020#issuecomment-1419535610
- Fixes https://github.com/seanmonstar/warp/issues/1015

🧹 Fix todos example  and ws test compilation error

---

.github/workflows/ci.yml

The toolchain is now installed with [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).

Replace unmaintained/outdated github actions

---

src/filters/multipart.rs

updated Part.content_type() to return Mime.as_ref() string

---

src/filters/multipart.rs
tests/multipart.rs

The current implementation of `multipart::form` requires that the `Content-Length` header exists. However, there are valid situations where this is not the case, for example when `Transfer-Encoding` header is present. See e.g. [RFC2616, section 4.4](https://datatracker.ietf.org/doc/html/rfc2616#section-4.4).
This PR adds an option to not check the content length, thus allowing the `multipart::form` filter to be used in cases where `Content-Length` header is not present. The change does not break the existing API.

Add option to ignore content-length with multipart body

---

src/reply.rs

#878 was originally meant to work with this change, however #458 which originally provided it was closed after #878 was merged. And so, I'm providing a minimal subset of #458 to merge. I'm leaving the example changes from #458 up to a future pr, since those could be subject to discussions unrelated to this particular change.
**Changes**:
- Implemented `Reply` for `Result<impl Reply, impl Reply>`.

Implemented Reply for Result<impl Reply, impl Reply>

---

examples/multipart.rs

example: multipart is wrongly using Buf::chunk

---

examples/stream.rs
src/filters/body.rs

As of right now it didn't look like there was example usage for this functionality. It took me some trial and error to figure out the typing for the Stream so that I could pass it into a handler function like this. This example hopefully avoids similar headaches for others.

Add example (and doc reference) for warp::body::stream()

---

src/filters/any.rs
src/filters/fs.rs
src/filters/log.rs
src/filters/reply.rs
src/filters/sse.rs
src/filters/trace.rs
src/filters/ws.rs
src/lib.rs
src/redirect.rs
src/test.rs

This commit fixes the "Build docs" CI step.
Failure example: https://github.com/seanmonstar/warp/actions/runs/5942488679/job/16116874741

Fix docs build

---

src/filter/boxed.rs
src/filters/any.rs
src/filters/cors.rs
src/filters/log.rs
src/filters/multipart.rs
src/filters/path.rs

A number of functions return structs that (indirectly) implement the `Filter` trait. After not finding an according reference in the documentation for quite a while, I had to look into the code to actually figure out what was going on. In this pull-request I've added some references to the Filter trait in hope it will help point readers into the right direction.

Add references to `Filter` in documentation

---

Cargo.toml

`rustls-pemfile` seems to be only used in tls feature.

deps: move rustls-pemfile crate to tls feature

---

Cargo.toml

In a `Cargo.toml`, the dependency versions mean that those versions are the minimum versions required for the project to build.
Sadly, the minimum versions that are given right now will cause compiler errors.
This can be checked through the tool [`cargo-minimal-versions`](https://crates.io/crates/cargo-minimal-versions).
This change modifies the minimal versions so that `cargo minimal-versions check` now succeeds.

Fix `cargo minimal-versions check`

---

Cargo.toml
src/reject.rs

Updates dependencies: `tokio-tungstenite` 0.21, `tracing-log` 0.2 and `async-compression` 0.4.5.

deps: update tokio-tungstenite, tracing-log and async-compression dependency

---

Cargo.toml

If hyper-util 0.1.11 is in the build tree then you get the following error:
```
error[E0599]: no method named `watcher` found for struct `GracefulShutdown` in the current scope
--> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/warp-0.4.1/src/server.rs:368:45
|
368 |                 let watcher = graceful_util.watcher();
|                                             ^^^^^^^
|
help: there is a method `watch` with a similar name, but with different arguments
--> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hyper-util-0.1.11/src/server/graceful.rs:32:5
|
32  |     pub fn watch<C: GracefulConnection>(&self, conn: C) -> impl Future<Output = C::Output> {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
For more …
```

Move to minimum working hyper util

---

Cargo.toml

Similar to #1128, but [for `http-body-util`](https://github.com/seanmonstar/warp/pull/1128#issuecomment-3164550418).
```rust
error[E0432]: unresolved import `http_body_util::BodyDataStream`
--> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/warp-0.4.0/src/filters/body.rs:14:5
|
14 | use http_body_util::BodyDataStream;
|     ^^^^^^^^^^^^^^^^--------------
|     |               |
|     |               help: a similar name exists in the module: `BodyStream`
|     no `BodyDataStream` in the root
```

Bump `http-body-util` min version to 0.1.2

---

.github/workflows/ci.yml

Updates to `actions/checkout` v4.

ci: update to actions/checkout@v4

---

Cargo.toml
src/bodyt.rs
src/filter/service.rs
src/filters/compression.rs
src/lib.rs

Makes hyper optional dependency.

deps: make hyper optional dependency
